src/flashcards/cards/urls.py
from django.conf.urls import url

from . import views

app_name = 'cards'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^flashcard$', views.list, name='list'),
    url(r'^flashcard/definition$', views.definition, name='definition'),
    url(r'^flashcard/create$', views.create, name='create'),
    url(r'^flashcard/update/(?P<card_id>.+)$', views.update, name='update'),
    url(r'^flashcard/guess/correct$', views.guess_correctly, name='guess_correctly'),
    url(r'^flashcard/guess/incorrect$', views.guess_incorrectly, name='guess_incorrectly'),
]

src/flashcards/flashcards/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'flashcards'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^flashcard$', views.list, name='list'),
    url(r'^flashcard/(?P<flashcard_id>.+)/definition$', views.definition, name='definition'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/flashcards/cards/models.py
from django.db import models
from datetime import datetime, timedelta

BUCKETS = [
  timedelta(seconds=0),    # bin 0
  timedelta(seconds=5),    # bin 1
  timedelta(seconds=25),   # bin 2
  timedelta(minutes=2),    # bin 3
  timedelta(minutes=10),   # bin 4
  timedelta(hours=1),      # bin 5
  timedelta(hours=5),      # bin 6
  timedelta(days=1),       # bin 7
  timedelta(days=5),       # bin 8
  timedelta(days=25),      # bin 9
  timedelta(days=30*4),    # bin 10 - approximately four months
  timedelta(days=365*300), # bin 11 - impure, but pragmatic
]

class Flashcard(models.Model):
  word = models.CharField(max_length=100, blank=False)
  definition = models.TextField(max_length=500, blank=False)
  bucket_number = models.IntegerField(default=0, blank=False)
  visible_after = models.DateTimeField()
  created_at = models.DateField(auto_now_add=True)
  failure_count = models.IntegerField(default=0, blank=False)

  def add_failure(self):
    self.failure_count = self.failure_count + 1
    self.bucket_number = 1
    self.__reset_bucket_timer()
  
  def increment_bucket(self):
    self.bucket_number = self.bucket_number + 1
    self.__reset_bucket_timer()
  
  def __reset_bucket_timer(self):
    self.visible_after = datetime.utcnow() + BUCKETS[self.bucket_number]

  def __str__(self):
    return '%s: %s' % (self.word, self.definition)

src/flashcards/cards/forms.py
from django.forms import ModelForm, TextInput, Textarea
from .models import Flashcard

class FlashcardForm(ModelForm):
  class Meta: 
    model = Flashcard
    fields = ['word', 'definition']
    widgets = {
      'word': TextInput(attrs={'placeholder': 'word'}),
      'definition': Textarea(attrs={
        'placeholder': "a single distinct meaningful element of speech or writing, used with others to form a sentence and typically shown with a space on either side when written or printed."
      })
    }

src/flashcards/cards/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from .actions import next_card, \
                     list_cards, \
                     guess_definition_correctly, \
                     guess_definition_incorrectly, \
                     create_card, \
                     update_card, \
                     get_card
from .forms import FlashcardForm
from .models import Flashcard

def index(request):
  return render(request, 'cards/index.html', next_card())

def definition(request):
  return render(request, 'cards/definition.html', next_card())

def list(request):
  starts_with = request.GET.get('q', '')
  cards = list_cards(starts_with)

  return render(request, 'cards/list.html', {
    'should_show_search': starts_with == '' and len(cards) > 0, 
    'create_form': FlashcardForm(), 
    'starts_with': starts_with, 
    'results': [{
      'form': FlashcardForm(instance=card),
      'card': card
    } for card in cards]
  })

def guess_correctly(request):
  if request.method == 'POST':
    guess_definition_correctly()
  return redirect(reverse('cards:index'))

def guess_incorrectly(request):
  if request.method == 'POST':
    guess_definition_incorrectly()
  return redirect(reverse('cards:index'))

def create(request):
  if request.method == 'POST':
    form = FlashcardForm(request.POST)
    new_card = form.save(commit=False)
    create_card(new_card)

    if form.is_valid():
      return redirect(reverse('cards:list'))
  return render(request, 'cards/new.html')

def update(request, card_id):
  if request.method == 'POST':
    card = get_card(card_id)
    form = FlashcardForm(request.POST, instance=card)
    card = form.save(commit=False)
    update_card(card)

    if form.is_valid():
      return redirect(reverse('cards:list'))
  return render(request, 'cards/new.html')

src/flashcards/cards/templates/cards/_card_form.html
<div class="flashcard flashcard-edit">
  <form method="POST" action="{% url 'cards:update' card.id %}">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="button">Save</button>
  </form>
  {% spaceless %}
  <span class="bucket">{{ card.bucket_number }}</span>
  <span class="failures">
    {% for _ in ''|center:card.failure_count %}&#10006;{% empty %}&nbsp;{% endfor %}
  </span>
  {% endspaceless %}
</div>

src/flashcards/cards/templates/cards/definition.html
{% extends '_base.html' %}

{% block body %}
<div class="app-review">
  {% if card %}
  <div class="flashcard flashcard-large flashcard-back">
    <span>{{ card.word }}</span>
    <p>{{ card.definition }}</p>
  </div>
  <form method="POST" action="{% url 'cards:guess_incorrectly' %}">
    {% csrf_token %}
    <button class="button button-negative">I didn't get it.</button>
  </form>
  <form method="POST" action="{% url 'cards:guess_correctly' %}">
    {% csrf_token %}
    <button class="button">I got it.</button>
  </form>
  {% endif %}
</div>
{% endblock %}

src/flashcards/cards/templates/cards/index.html
{% extends '_base.html' %}

{% block body %}
<div class="app-review">
  {% if card %}
    <div class="flashcard flashcard-large flashcard-front">
      <span>{{ card.word }}</span>
    </div>
    <a class="button" href="{% url 'cards:definition' %}">Show the definition.</a>
  {% elif has_pending_cards %}
    <h2>You are temporarily done; please come back later to review more words.</h2>
  {% elif has_any_cards %}
    <h2>You have no more words to review; you are permanently done!</h2>
  {% else %}
    <h2>You haven't created any cards; click <a href="{% url 'cards:list' %}">manage</a> to begin.</h2>
  {% endif %}
</div>
{% endblock %}

src/flashcards/cards/templates/cards/list.html
{% extends '_base.html' %}

{% block body %}
<div class="app-manage">
  {% if should_show_search %}
  <form class="search-form" method="GET" action="{% url 'cards:list' %}">
    <button class="button" type="submit" autofocus>Search</button>
    <input type="text" name="q" value="{{ starts_with }}" placeholder="Search for word..." />
  </form>
  {% endif %}
  <div class="flashcard-list">
    <div class="flashcard flashcard-edit">
      <form method="POST" action="{% url 'cards:create' %}">
        {% csrf_token %}
        {{ create_form }}
        <button type="submit" class="button">Create</button>
      </form>
      {% spaceless %}
      <span class="bucket">0</span>
      <span class="failures">&nbsp;</span>
      {% endspaceless %}
    </div>
    {% for result in results %}
      {% include 'cards/_card_form.html' with card=result.card form=result.form %}
    {% endfor %}
  </div>
</div>
{% endblock %}

src/flashcards/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <title>Flash Cards</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'cards/css/reset.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'cards/css/styles.css' %}" />
    {% endblock %}
  </head>
  <body>
    <div class="container">
      <header>
        <a href="/flashcard">Manage</a>
        <h1><a href="/">Flashcards</a></h1>
      </header>
      {% block body %}
      {% endblock %}
    </div>
  </body>
</html>